// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("SolidityProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("SolidityProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing SolidityProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "SolidityProvider.Runtime"
    let [<Literal>] AssemblyProduct = "SolidityProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing SolidityProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
