// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AbiTypeProviderFromTruffle.Runtime")>]
[<assembly: AssemblyProductAttribute("AbiTypeProviderFromTruffle")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing AbiTypeProviderFromTruffle.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AbiTypeProviderFromTruffle.Runtime"
    let [<Literal>] AssemblyProduct = "AbiTypeProviderFromTruffle"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing AbiTypeProviderFromTruffle."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
