// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AbiTypeProvider.Runtime")>]
[<assembly: AssemblyProductAttribute("AbiTypeProvider")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing AbiTypeProvider.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AbiTypeProvider.Runtime"
    let [<Literal>] AssemblyProduct = "AbiTypeProvider"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing AbiTypeProvider."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
